import { useState, type ReactNode } from "react";

type IconName = "shield" | "grid" | "radar" | "cloud" | "alert" | "check" | "arrow" | "menu" | "close" | "lock" | "scan" | "bolt";

function Icon({ name, size = 20 }: { name: IconName; size?: number }) {
  const paths: Record<IconName, ReactNode> = {
    shield: <><path d="M12 3 4.5 6v5.4c0 4.7 3.1 8.1 7.5 9.6 4.4-1.5 7.5-4.9 7.5-9.6V6L12 3Z"/><path d="m9 12 2 2 4-4"/></>,
    grid: <><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,
    radar: <><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><path d="m12 12 6-6M12 3v2M3 12h2"/></>,
    cloud: <path d="M17.5 19H7a5 5 0 0 1-.6-10A7 7 0 0 1 20 11.5 3.8 3.8 0 0 1 17.5 19Z"/>,
    alert: <><path d="M10.3 3.8 2.7 17a2 2 0 0 0 1.7 3h15.2a2 2 0 0 0 1.7-3L13.7 3.8a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4M12 17h.01"/></>,
    check: <path d="m5 12 4 4L19 6"/>, arrow: <><path d="M5 12h14M13 6l6 6-6 6"/></>, menu: <><path d="M4 7h16M4 12h16M4 17h16"/></>, close: <><path d="m6 6 12 12M18 6 6 18"/></>,
    lock: <><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>,
    scan: <><path d="M4 7V5a1 1 0 0 1 1-1h2M17 4h2a1 1 0 0 1 1 1v2M20 17v2a1 1 0 0 1-1 1h-2M7 20H5a1 1 0 0 1-1-1v-2"/><circle cx="12" cy="12" r="3"/></>, bolt: <path d="m13 2-9 12h7l-1 8 9-12h-7l1-8Z"/>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}

const features = [
  { icon: "radar" as IconName, title: "See every risk", text: "Continuously map assets, identities, and exposures across AWS, Azure, and Google Cloud." },
  { icon: "scan" as IconName, title: "Prioritize what matters", text: "Attack-path analysis connects scattered signals so your team fixes exploitable risk first." },
  { icon: "bolt" as IconName, title: "Respond at cloud speed", text: "Automated workflows contain threats in seconds, with the context your engineers need." },
];

const plans = [
  { name: "Visibility", desc: "For teams building a cloud security baseline.", monthly: 29, features: ["Up to 250 cloud resources", "Multi-cloud inventory", "Compliance monitoring", "7-day data retention"] },
  { name: "Control", desc: "For growing teams reducing active risk.", monthly: 79, popular: true, features: ["Up to 2,500 cloud resources", "Attack-path analysis", "Automated remediation", "90-day data retention", "Slack and Jira workflows"] },
  { name: "Scale", desc: "For complex, high-velocity environments.", monthly: 0, features: ["Unlimited cloud resources", "Custom policies and roles", "SIEM and API access", "Dedicated security architect", "Enterprise SLA"] },
];

function Dashboard() {
  return <div className="dashboard" aria-label="Nimbus cloud security analytics dashboard preview">
    <aside className="dash-sidebar"><div className="dash-mark"><Icon name="shield" size={19}/></div>{["grid", "radar", "cloud", "alert", "lock"].map((item, i) => <div key={item} className={`dash-nav-icon ${i === 1 ? "active" : ""}`}><Icon name={item as IconName} size={17}/></div>)}</aside>
    <div className="dash-main"><div className="dash-topbar"><div><span>Overview</span><small> / Security posture</small></div><div className="dash-user"><span>Last 24 hours</span><i>AM</i></div></div>
      <div className="dash-content"><div className="dash-heading"><div><h3>Security posture</h3><p>All cloud environments</p></div><button>Export report</button></div>
        <div className="metric-row"><div><small>Security score</small><strong>92<span>/100</span></strong><em>+8.4%</em></div><div><small>Protected assets</small><strong>12,480</strong><em>+241</em></div><div><small>Critical findings</small><strong>07</strong><em className="risk">-12</em></div></div>
        <div className="dash-grid"><section className="chart-panel"><header><div><strong>Risk trend</strong><small>Findings by severity</small></div><span>30 days</span></header><div className="chart"><div className="y-labels"><span>120</span><span>80</span><span>40</span><span>0</span></div><svg viewBox="0 0 500 175" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#805dff" stopOpacity=".36"/><stop offset="1" stopColor="#805dff" stopOpacity="0"/></linearGradient></defs><path className="area" d="M0 55 C35 45 52 73 87 68 S140 42 175 59 S220 105 255 89 S300 64 335 80 S385 40 420 49 S465 20 500 31 L500 175 L0 175Z"/><path className="line" pathLength="1" d="M0 55 C35 45 52 73 87 68 S140 42 175 59 S220 105 255 89 S300 64 335 80 S385 40 420 49 S465 20 500 31"/><path className="line-secondary" pathLength="1" d="M0 112 C50 102 77 118 119 109 S180 119 226 103 S284 112 329 99 S398 107 447 89 S477 92 500 82"/></svg><div className="x-labels"><span>May 01</span><span>May 08</span><span>May 15</span><span>May 22</span><span>May 29</span></div></div></section>
          <section className="score-panel"><header><strong>Coverage</strong><span>Live</span></header><div className="donut"><div><b>96%</b><small>monitored</small></div></div>{["AWS", "Azure", "GCP"].map((x,i)=><div className="coverage-row" key={x}><span><i className={i===1?"azure":i===2?"gcp":"aws"}/>{x}</span><b>{["4,821","3,644","4,015"][i]}</b></div>)}</section></div>
        <section className="findings"><header><strong>Priority findings</strong><span>View all 24</span></header><div className="finding"><i className="critical"/><div><b>Public database with sensitive data</b><small>prod-eu-west-1 / customer-records</small></div><span>Critical</span><time>2m ago</time></div><div className="finding"><i className="medium"/><div><b>Overprivileged IAM service role</b><small>aws-main / deployment-runner</small></div><span>Medium</span><time>14m ago</time></div></section>
      </div></div></div>;
}

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false); const [annual, setAnnual] = useState(true);
  return <main>
    <section className="hero" id="home"><header className="site-header"><a href="#home" className="brand" aria-label="Nimbus home"><span><Icon name="shield" size={22}/></span>NIMBUS</a><nav className={menuOpen ? "open" : ""} aria-label="Main navigation"><a href="#platform" onClick={()=>setMenuOpen(false)}>Platform</a><a href="#pricing" onClick={()=>setMenuOpen(false)}>Pricing</a><a href="#security" onClick={()=>setMenuOpen(false)}>Why Nimbus</a><a href="#contact" onClick={()=>setMenuOpen(false)}>Resources</a></nav><div className="header-actions"><a href="#contact" className="login">Sign in</a><a href="#pricing" className="button button-small">Start free</a></div><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label={menuOpen?"Close menu":"Open menu"} aria-expanded={menuOpen}><Icon name={menuOpen?"close":"menu"}/></button></header>
      <div className="hero-dashboard" aria-hidden="true"><Dashboard/></div><div className="hero-shade"/><div className="hero-content"><div className="eyebrow"><span/>Cloud security, unified</div><h1>Secure every cloud.<br/><em>Move without fear.</em></h1><p>Nimbus reveals your most dangerous cloud risks and gives your team the context to fix them before attackers find them.</p><div className="hero-actions"><a className="button" href="#pricing">Start free for 14 days <Icon name="arrow" size={18}/></a><a className="text-link" href="#platform">See the platform <span>01:42</span></a></div><small className="hero-note"><Icon name="check" size={14}/> No credit card required</small></div><div className="scroll-line"><span/>Scroll to explore</div></section>
    <section className="trust" aria-label="Trusted customers"><p>Protecting cloud teams at</p><div className="logos"><span>VERCEL</span><span>wandb</span><span>brex</span><span>Webflow</span><span>RAMP</span><span>RETELL</span></div></section>
    <section className="platform-section" id="platform"><div className="section-intro"><span className="section-kicker">One security graph</span><h2>From cloud noise<br/>to clear action.</h2><p>Nimbus connects configuration, identity, vulnerability, and runtime signals in one living model of your cloud.</p></div><div className="features">{features.map((feature,i)=><article className="feature" key={feature.title} style={{"--delay":`${i*120}ms`} as React.CSSProperties}><div className="feature-number">0{i+1}</div><div className="feature-icon"><Icon name={feature.icon} size={25}/></div><h3>{feature.title}</h3><p>{feature.text}</p><a href="#contact">Explore capability <Icon name="arrow" size={16}/></a></article>)}</div></section>
    <section className="security-section" id="security"><div className="security-visual"><div className="orbit orbit-one"><i/><i/><i/></div><div className="orbit orbit-two"><i/><i/></div><div className="security-core"><Icon name="shield" size={42}/><span>Protected</span><b>12,480 assets</b></div></div><div className="security-copy"><span className="section-kicker">Built for your entire team</span><h2>Security that never slows engineering down.</h2><p>Give security teams complete control while developers get precise fixes inside the tools they already use.</p><ul><li><Icon name="check"/> Deploy read-only in under 10 minutes</li><li><Icon name="check"/> Zero agents across your cloud accounts</li><li><Icon name="check"/> SOC 2 Type II and ISO 27001 compliant</li></ul><a href="#contact" className="button button-dark">Explore Nimbus <Icon name="arrow" size={18}/></a></div></section>
    <section className="pricing-section" id="pricing"><div className="pricing-heading"><div><span className="section-kicker">Simple pricing</span><h2>Start secure.<br/>Scale with confidence.</h2></div><div className="billing-toggle" role="group" aria-label="Billing frequency"><button className={!annual?"active":""} onClick={()=>setAnnual(false)}>Monthly</button><button className={annual?"active":""} onClick={()=>setAnnual(true)}>Annual <span>-20%</span></button></div></div><div className="pricing-grid">{plans.map(plan=><article className={`price ${plan.popular?"featured":""}`} key={plan.name}>{plan.popular&&<div className="popular">Most popular</div>}<h3>{plan.name}</h3><p>{plan.desc}</p><div className="price-value">{plan.monthly?<><sup>$</sup>{annual?Math.round(plan.monthly*.8):plan.monthly}<small>/ resource<br/>/ month</small></>:<><strong>Custom</strong><small>Built around<br/>your cloud</small></>}</div><a href="#contact" className={`button ${plan.popular?"":"button-outline"}`}>{plan.monthly?"Start free":"Talk to sales"}<Icon name="arrow" size={17}/></a><ul>{plan.features.map(item=><li key={item}><Icon name="check" size={16}/>{item}</li>)}</ul></article>)}</div></section>
    <section className="cta" id="contact"><div><span className="section-kicker">Your cloud is moving fast</span><h2>Secure it even faster.</h2><p>Connect your first cloud account and see actionable risk in minutes.</p></div><a href="mailto:hello@nimbus.security" className="button button-light">Start your free trial <Icon name="arrow" size={18}/></a></section>
    <footer><a href="#home" className="brand brand-dark"><span><Icon name="shield" size={20}/></span>NIMBUS</a><p>Cloud security for teams that move.</p><div><a href="#platform">Platform</a><a href="#pricing">Pricing</a><a href="mailto:hello@nimbus.security">Contact</a></div><small>2026 Nimbus Security, Inc.</small></footer>
  </main>;
}
